source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
# activesupport 7.2.3.1 requires Ruby 3.1 or later.
ruby ">= 3.1.0"

# Exclude problematic versions of cocoapods that cause build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
# 7.2.3.1 is the first release below 8 with fixes for GHSA-2j26-frm8-cmj9,
# GHSA-cg4j-q9v8-6v38 and GHSA-89vf-4333-qx8v. CocoaPods requires activesupport < 8.
gem 'activesupport', '>= 7.2.3.1'
gem 'xcodeproj', '< 1.26.0'
