name: Demo CI
on: [ push, pull_request ]
jobs:
  demo-android-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5.7.0
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Build and pack SDK
        working-directory: sdk
        run: npm run build_pack_1

      - name: Install SDK into demo app
        working-directory: sdk
        run: npm run build_demo_2

      - name: Build Android app
        run: |
             cd android
             ./gradlew assembleDebug

  demo-ios-build:
    runs-on: macos-15
    defaults:
      run:
        working-directory: demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Select Xcode
        run: |
             sudo xcode-select -switch /Applications/Xcode_16.4.app
             xcodebuild -version

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Build and pack SDK
        working-directory: sdk
        run: npm run build_pack_1

      - name: Install SDK into demo app
        working-directory: sdk
        run: npm run build_demo_2

      - name: Install CocoaPods dependencies
        working-directory: demo/ios
        run: pod install

      - name: Build iOS app
        run: npx react-native build-ios
