name: Demo CI
on: [ push, pull_request ]
jobs:
  demo-android-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build SDK
        working-directory: sdk
        run: npm install

      - name: Install dependencies
        run: npm install --install-links

      - name: Build application
        run: |
             cd android
             ./gradlew assembleDebug

  demo-ios-build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build SDK
        working-directory: sdk
        run: npm install

      - name: Install dependencies
        run: npm install --install-links

      - name: Pod Install
        working-directory: demo/ios
        run: pod install

      - name: Build application
        run: npx react-native build-ios
